Repository jvegax/Acme-Toolkits, pull requests merged in 2022-05, with the labels that each got.

#161 Task-076: Done
  src/main/java/acme/entities/item/Item.java
  src/main/java/acme/features/inventor/item/InventorComponentListService.java
  src/main/java/acme/features/inventor/item/InventorItemController.java
  src/main/java/acme/features/inventor/item/InventorItemCreateService.java
  src/main/java/acme/features/inventor/item/InventorItemDeleteService.java
  src/main/java/acme/features/inventor/item/InventorItemListByToolkitService.java
  src/main/java/acme/features/inventor/item/InventorItemPublishService.java
  src/main/java/acme/features/inventor/item/InventorItemRepository.java
  src/main/java/acme/features/inventor/item/InventorItemShowService.java
  src/main/java/acme/features/inventor/item/InventorItemUpdateService.java
  src/main/java/acme/features/inventor/item/InventorToolListService.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/list.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messages-es.i18n
Labels: code 🧑‍💻

#162 Task-077: Done
  .classpath
  .project
  src/main/java/acme/entities/item/Item.java
  src/main/java/acme/entities/toolkit/Toolkit.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitController.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitCreateService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitDeleteService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitListService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitPublishService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitRepository.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitShowService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitUpdateService.java
  src/main/webapp/WEB-INF/resources/sample-data/toolkit.csv
  src/main/webapp/WEB-INF/views/inventor/toolkit/form.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/list.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit/messages-es.i18n
Labels: code 🧑‍💻

#170 Task-087:Done
  .classpath
  src/test/java/acme/testing/administrator/announcement/AdministratorAnnouncementCreateTest.java
  src/test/resources/administrator/announcement/create-negative.csv
  src/test/resources/administrator/announcement/create-positive.csv
Labels: test🧪

#175 Task 082 + Task 088
  src/main/java/acme/features/administrator/currency/AdministratorCurrencyController.java
  src/main/java/acme/features/administrator/currency/AdministratorCurrencyCreateService.java
  src/main/java/acme/features/administrator/spam/AdministratorSpamController.java
  src/main/java/acme/features/administrator/spam/AdministratorSpamCreateService.java
  src/main/webapp/WEB-INF/resources/sample-data/quantity.csv
  src/main/webapp/WEB-INF/resources/sample-data/toolkit.csv
  src/main/webapp/WEB-INF/views/administrator/currency/form.jsp
  src/main/webapp/WEB-INF/views/administrator/currency/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/currency/messages-es.i18n
  src/main/webapp/WEB-INF/views/administrator/spam/form.jsp
  src/main/webapp/WEB-INF/views/administrator/spam/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/spam/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitCreateTest.java
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitPublishTest.java
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitUpdateTest.java
  src/test/resources/inventor/toolkit/create-negative.csv
  src/test/resources/inventor/toolkit/create-positive.csv
Labels: code 🧑‍💻, test🧪

#181 Fixed spam test
  src/test/java/acme/testing/configuration/AuthenticatedAdministratorConfigurationListTest.java
Labels: code 🧑‍💻

#190 Hotfix-Task-048 : Done
  src/main/java/acme/features/inventor/patronageReport/InventorPatronageReportShowService.java
  src/main/webapp/WEB-INF/views/inventor/patronage-report/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-es.i18n
Labels: bug 🪲, code 🧑‍💻

#193 Hotfix/toolkit
  src/main/java/acme/features/any/toolkit/AnyToolkitListAllService.java
  src/main/java/acme/features/inventor/item/InventorItemRepository.java
  src/main/java/acme/features/inventor/patronage/InventorPatronageRepository.java
  src/main/java/acme/features/inventor/patronageReport/InventorPatronageReportShowService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitCreateService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitListService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitPublishService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitShowService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitUpdateService.java
  src/main/java/acme/features/patron/patronage/PatronPatronageCreateService.java
  src/main/webapp/WEB-INF/views/any/toolkit/list.jsp
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/form.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/list.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit/messages-es.i18n
  src/test/resources/inventor/toolkit/create-negative.csv
  src/test/resources/inventor/toolkit/create-positive.csv
  src/test/resources/inventor/toolkit/list.csv
  src/test/resources/inventor/toolkit/show.csv
Labels: bug 🪲, code 🧑‍💻

#194 Task 037 d4
  src/main/java/acme/features/any/userAccount/AnyUserAccountController.java
  src/main/java/acme/features/any/userAccount/AnyUserAccountListService.java
  src/main/java/acme/features/any/userAccount/AnyUserAccountRepository.java
  src/main/java/acme/features/any/userAccount/AnyUserAccountShowService.java
  src/main/webapp/WEB-INF/views/any/user-account/form.jsp
  src/main/webapp/WEB-INF/views/any/user-account/list.jsp
  src/main/webapp/WEB-INF/views/any/user-account/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/user-account/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: code 🧑‍💻

#197 Quantity Fixed
  src/main/java/acme/components/SpamModule.java
  src/main/java/acme/entities/toolkit/Toolkit.java
  src/main/java/acme/features/any/item/AnyItemController.java
  src/main/java/acme/features/any/item/AnyItemListByToolkitService.java
  src/main/java/acme/features/any/item/AnyItemRepository.java
  src/main/java/acme/features/any/item/AnyItemShowService.java
  src/main/java/acme/features/any/toolkit/AnyToolkitListAllService.java
  src/main/java/acme/features/any/toolkit/AnyToolkitRepository.java
  src/main/java/acme/features/any/toolkit/AnyToolkitShowService.java
  src/main/java/acme/features/any/userAccount/AnyUserAccountListService.java
  src/main/java/acme/features/authenticated/item/AuthenticatedComponentShowService.java
  src/main/java/acme/features/authenticated/item/AuthenticatedComponentToolShowService.java
  src/main/java/acme/features/inventor/item/InventorItemController.java
  src/main/java/acme/features/inventor/item/InventorItemListByToolkitService.java
  src/main/java/acme/features/inventor/item/InventorItemPublishService.java
  src/main/java/acme/features/inventor/item/InventorItemRepository.java
  src/main/java/acme/features/inventor/item/InventorToolListService.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityController.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityCreateService.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityDeleteService.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityListService.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityRepository.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityShowService.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityUpdateService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitCreateService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitDeleteService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitListService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitPublishService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitRepository.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitShowService.java
  src/main/java/acme/features/inventor/toolkit/InventorToolkitUpdateService.java
  src/main/java/acme/features/moneyExchange/MoneyExchangePerform.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/resources/sample-data/quantity.csv
  src/main/webapp/WEB-INF/resources/sample-data/toolkit.csv
  src/main/webapp/WEB-INF/views/any/toolkit/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/quantity/form.jsp
  src/main/webapp/WEB-INF/views/inventor/quantity/list.jsp
  src/main/webapp/WEB-INF/views/inventor/quantity/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/quantity/messages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/toolkit/form.jsp
  src/test/java/acme/testing/administrator/announcement/AdministratorAnnouncementCreateTest.java
  src/test/resources/any/item/components.csv
  src/test/resources/any/item/tools.csv
Labels: code 🧑‍💻

#202 Arregla los botones de toolkit e item
  reports/domain_diagram.uxf
  src/main/java/acme/entities/item/Item.java
  src/main/java/acme/entities/quantity/Quantity.java
  src/main/java/acme/features/inventor/quantity/InventorQuantityCreateService.java
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/toolkit/form.jsp
Labels: code 🧑‍💻
